set sqlite temporal directory
I have a 4.5 million set of particles, when running the protocol "localrec extract particles2 I get the error Error: database or disk is full
It seems that the executed SQL command is: SELECT * FROM Objects WHERE 1 ORDER BY c09,c03,id ASC ;
This command creates a temporary file several times larger then the database (which is 8.8 Gb), this temporary file is too large for my /tmp directory
So I have modified the mapper such that it uses the local dir as temporary directory.

=====
SQL code that shows that the problem is indeed the temp directory
carmen@clark-cinco:~$ sqlite3 /home/carmen/ScipionUserData/projects/MartaM_Ad5_delta7/Runs/006674_ProtLocalizedRecons/coordinates.sqlite 
SQLite version 3.27.2 2019-02-25 16:06:06
Enter ".help" for usage hints.
sqlite> .output kk      -- rediret output to file 
sqlite> SELECT * FROM Objects WHERE 1 ORDER BY c09,c03,id ASC ;  -- excute command
Error: database or disk is full   -- it fails :-(
sqlite> PRAGMA temp_store_directory = '.'; -- set current dir as temporary directory using a pragma command
sqlite> SELECT * FROM Objects WHERE 1 ORDER BY c09,c03,id ASC ; -- execute command
sqlite>  -- now it does finish :-)